### ISSUE TITLE
cannot start app

### ISSUE THREAD

**Issue by jgrabitzky** [squancy/zaccord#30]
Hello
i have a error

node app.js
[ 470, 450, 450 ] [ 250, 220, 120 ]
/root/zaccord/node_modules/client-sessions/lib/client-sessions.js:548
    throw new Error("cannot set up sessions without a secret "+
    ^

Error: cannot set up sessions without a secret or encryptionKey/signatureKey pair
    at clientSessionFactory (/root/zaccord/node_modules/client-sessions/lib/client-sessions.js:548:11)
    at createSession (/root/zaccord/src/js/includes/createSession.js:7:17)
    at Object.<anonymous> (/root/zaccord/app.js:113:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

any idea ?

many thanks

**Comment by squancy** [comment]
Hi,

You need to initialize the empty variables in `/src/js/includes/constants.js`, including the secret session string that gave you an error.
